### ISSUE TITLE
Csak néhány ötlet

### ISSUE THREAD

**Issue by CryptoSyphon** [MicroCoinHU/MicroCoinWallet#6]
Lenne egy-két ötletem a desktop tárcával kapcsolatban.
- [ ] ~~Az egyik, be lehessen állítani a Windows-zal együtt indulás lehetőségét (persze tudom, hogy ott van a Futtatás -> shell:startup lehetősége, de hát akkor is 😄 ).~~
- [x] A másik, hogy le lehessen tenni az értesítési területre az óra mellé úgy, hogy a taskbar-on nincs ott.
- [x] A harmadik, hogy asztali értesítést jelenítene meg, ha utalás érkezik a számlára. Ez így tök jó lenne, mert folyamatosan frissítené magát és csomópontként is működne úgy, hogy észre sem venné az ember.

**Comment by Pethical** [comment]
- [x] Le lehessen tenni az értesítési területre az óra mellé úgy, hogy a taskbar-on nincs ott.
- [x] Asztali értesítést jelenítene meg, ha utalás érkezik a számlára.
- [ ] Be lehessen állítani a Windows-zal együtt indulás lehetőségét
